### ISSUE TITLE
'!Firefox' menu

### ISSUE THREAD

**Issue by probonopd** [airyxos/Firefox_app#2]
When running this version of Firefox on helloSystem, I am seeing a "!Firefox" menu before "File".

![image](https://user-images.githubusercontent.com/2480569/140661195-941f2dec-cf09-460e-a227-e68dca4faa57.png)

Is this done inside this repo? I'd actually need a version without this.

**Comment by mszoek** [comment]
Yes - the menus are reorganized by this patch:
`https://github.com/airyxos/Firefox_app/blob/main/patch-browser_menubar`

So just omit that from the build if you don't want the "application" menu. I do need that for airyxOS as it creates the bolded "Firefox" menu with the About/Quit/etc options on it.

**Comment by probonopd** [comment]
Thank you very much.

**Comment by probonopd** [comment]
@mszoek since no existing binaries will have that menu in that place, wouldn't be a more sensible approach to re-shuffle the menus on-the-fly when the menubar receives them via D-Bus? Then you would get that extra icon not just for this one app, but for all of them...

**Comment by probonopd** [comment]
I tried building Firefox on Cirrus CI and from how I read the logs the build "almost" succeeded but not quite:
https://cirrus-ci.com/task/5185344850100224?logs=main#L9174

Have you ran into this before?

**Comment by mszoek** [comment]
> @mszoek since no existing binaries will have that menu in that place, wouldn't be a more sensible approach to re-shuffle the menus on-the-fly when the menubar receives them via D-Bus? Then you would get that extra icon not just for this one app, but for all of them...

Possibly, but I am not sure they're deterministic enough to do that reliably. This is just a stop-gap until I can get the Mac version building so I don't plan to spend a lot of effort on it.

**Comment by mszoek** [comment]
> I tried building Firefox on Cirrus CI and from how I read the logs the build "almost" succeeded but not quite: https://cirrus-ci.com/task/5185344850100224?logs=main#L9174
> 
> Have you ran into this before?

No... some kind of issue with libpci from the looks of it.

**Comment by probonopd** [comment]
> This is just a stop-gap until I can get the Mac version building

I like _that_ goal setting! :+1:
